### ISSUE TITLE
Man pages

### ISSUE THREAD

**Issue by Morganamilo** [Morganamilo/paccat#6]

**Comment by pickfire** [comment]
@Morganamilo Can you please put `hacktoberfest-accepted` label?

**Comment by Morganamilo** [comment]
The whole repo is tagged as hacktober fest. I did merge this late but I would assume it still counts as it was oppened in october.

**Comment by pickfire** [comment]
![image](https://user-images.githubusercontent.com/4687791/139970655-8d22f9ce-6fa7-4cfb-8c1e-df1be8e36d06.png)

But I guess it's fine, I already have 4 pull requests.
